In [1]:
import geocoder
import numpy as np
import pandas as pd
import folium
import pydeck as pdk
from geocode import get_place_data,str_list_to_numpy_array



#place = '清水寺'
#ret = geocoder.osm(place, timeout=1.0)
#print(ret)
#print(dir(ret))
#print(place, ret.latlng)

ModuleNotFoundError: No module named 'geocode'

In [2]:
places_list = ['清水寺','京都駅','金閣寺']
a = get_place_data(places_list)

In [3]:
a = np.array(a)
place_type ,lat, long = a[:,0], str_list_to_numpy_array(a[:,1]), str_list_to_numpy_array(a[:,2])
place_type ,lat, long

(array(['place_of_worship', 'station', 'place_of_worship'], dtype='<U32'),
 array([34.994303  , 34.9853497 , 35.03952925]),
 array([135.78443889, 135.758766  , 135.72953725]))

[34.994303, 34.9853497, 35.03952925]

In [29]:
#2次元の地図 
folium_map = folium.Map(location=[lat[0], long[0]], zoom_start=12)

for place_,lat_,long_ in zip(places_list,lat,long):
    folium.Marker(location=[lat_, long_],popup = place_ ).add_to(folium_map)
#folium_map

In [25]:
df = pd.DataFrame()
#df['name'] = [f"{places_list[i]}-{places_list[i+1]}" for i in range(len(lat) - 1)]
#df['path'] = [[[lat[i],long[0]] ,[lat[i+1], long[i+1]]] for i in range(len(lat) - 1)]
#df['time'] = [i+1 for i in range(len(lat)  - 1)] 
#df['color'] = [(237, 28, 36) for i in range(len(lat)  - 1)]
df['lat'] = lat
df['long'] = long
#a = df.path[0]
#b= df.path[1]
df

lat        long
0  34.994303  135.784439
1  34.985350  135.758766
2  35.039529  135.729537

In [28]:
layers=[
        pdk.Layer(
            'ScatterplotLayer',
            data=df,
            get_position='[lat, long]',
            #get_fill_color="ward_color",
            get_fill_color=[180, 0, 200,150],
            get_radius=100,
        )]


fig = pdk.Deck(
            map_style='mapbox://styles/mapbox/stree',
            initial_view_state= pdk.ViewState(latitude=lat[0],longitude=long[0], zoom=14,patch = 50),
            layers = layers
            )
#fig

In [6]:
layer= pdk.Layer(
    type = "PathLayer",
    data=df,
    pickable=True,
    get_color="color",
    width_scale=20,
    width_min_pixels=2,
    get_path="path",
    get_width=5,
)
#3次元の地図
view_state = pdk.ViewState(latitude=lat[0],longitude=long[0], zoom=10)
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.show()

DeckGLWidget(carto_key=None, custom_libraries=[], google_maps_key=None, json_input='{"initialViewState": {"lat…

DeckGLWidget(carto_key=None, custom_libraries=[], google_maps_key=None, json_input='{"initialViewState": {"lat…

In [77]:
df.head()


name           color  \
0            Richmond - Millbrae   (237, 28, 36)   
1             Fremont - Richmond  (250, 166, 26)   
2      Pittsburg/Bay Point - SFO   (255, 232, 0)   
3  Dublin/Pleasanton - Daly City   (0, 174, 239)   
4            Fremont - Daly City   (77, 184, 72)   

                                                path  
0  [[-122.3535851, 37.9360513], [-122.3179784, 37...  
1  [[-122.353165, 37.936887], [-122.317269, 37.92...  
2  [[-121.945154, 38.018914], [-122.024597, 38.00...  
3  [[-121.900367, 37.701695], [-121.928099, 37.69...  
4  [[-121.9764, 37.557355], [-122.017867, 37.5912...

In [31]:
import pandas as pd
import pydeck as pdk

DATA_URL = "https://raw.githubusercontent.com/visgl/deck.gl-data/master/website/bart-lines.json"
df = pd.read_json(DATA_URL)


def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i : i + 2], 16) for i in (0, 2, 4))


df["color"] = df["color"].apply(hex_to_rgb)
df = df.iloc[:2]
df['path'][0] = a
df['path'][1] = b


view_state = pdk.ViewState(latitude=lat[0],longitude=long[0], zoom=10)

layer = pdk.Layer(
    type="PathLayer",
    data=df,
    pickable=True,
    get_color="color",
    width_scale=20,
    width_min_pixels=2,
    get_path="path",
    get_width=20,
)

r = pdk.Deck(layers=[layer], initial_view_state=view_state, tooltip={"text": "{name}"})
r

{"initialViewState": {"latitude": 34.994303, "longitude": 135.7844388864188, "zoom": 10}, "layers": [{"@@type": "PathLayer", "data": [{"color": [237, 28, 36], "name": "Richmond - Millbrae", "path": [[34.994303, 135.7844388864188], [34.9853497, 135.758766]]}, {"color": [250, 166, 26], "name": "Fremont - Richmond", "path": [[34.9853497, 135.7844388864188], [35.03952925, 135.72953725309281]]}], "getColor": "@@=color", "getPath": "@@=path", "getWidth": 20, "id": "bb99e286-ab4f-4a7a-8a69-08a7d1de776f", "pickable": true, "widthMinPixels": 2, "widthScale": 20}], "mapProvider": "carto", "mapStyle": "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json", "views": [{"@@type": "MapView", "controller": true}]}

In [27]:
df

name           color  \
0  Richmond - Millbrae   (237, 28, 36)   
1   Fremont - Richmond  (250, 166, 26)   

                                                path  
0  [[34.994303, 135.7844388864188], [34.9853497, ...  
1  [[34.9853497, 135.7844388864188], [35.03952925...

In [15]:
b = df.path[0]

In [16]:
type(b)

list

In [17]:
type(a)

list

## 最短経路


In [14]:
import pulp
from scipy.spatial import distance
import pandas as pd

df = pd.DataFrame()
df['lat'] = [140.1,130.33,140.3]
df['long'] = [33.2, 34.5, 33.3]
df.index = range(1,len(df) + 1 )
df.values

array([[140.1 ,  33.2 ],
       [130.33,  34.5 ],
       [140.3 ,  33.3 ]])

In [19]:
path_ = []
for i in df.index:
    for j in df.index:
        if i < j:
            path_.append([i,j])
path_

[[1, 2], [1, 3], [2, 3]]

In [39]:
p = pulp.LpProblem('tsp_mip', pulp.LpMinimize)
path_len = len(path_)
#経路の行列を作成
w = distance.pdist(df.values) # dist(u=X[i], v=X[j]) is computed and stored in entry m * i + j - ((i + 2) * (i + 1)) // 2.
w

array([ 9.85610978,  0.2236068 , 10.04195698])

In [40]:
x = [ pulp.LpVariable(f'x{path_[i][0]}_{path_[i][1]}', cat='Binary') for i in range(path_len)]
p += pulp.lpDot(w, x)

# set constrains
for i in range(path_len):
    p += x[i] <= 1
p+= pulp.lpSum(x) == len(path_) - 1
p.solve()


Welcome to the CBC MILP Solver 
Version: 2.10.3 
Build Date: Dec 15 2019 

command line - /Users/shibuya/myGitHub/TravelPlan/venv/lib/python3.7/site-packages/pulp/apis/../solverdir/cbc/osx/64/cbc /var/folders/4h/6p_tnk45467fqc01zbhlyj900000gp/T/3d0f5681cea949d9bf79396a70d92992-pulp.mps timeMode elapsed branch printingOptions all solution /var/folders/4h/6p_tnk45467fqc01zbhlyj900000gp/T/3d0f5681cea949d9bf79396a70d92992-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 9 COLUMNS
At line 25 RHS
At line 30 BOUNDS
At line 34 ENDATA
Problem MODEL has 4 rows, 3 columns and 6 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 10.0797 - 0.00 seconds
Cgl0004I processed model has 1 rows, 3 columns (3 integer (3 of which binary)) and 3 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 10.0797
Cbc0038I Before mini branch and bound, 3 integers at bound fix

1

ed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of 10.0797 - took 0.00 seconds
Cbc0012I Integer solution of 10.079717 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective 10.079716577983, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 10.0797 to 10.0797
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was

In [47]:
p.objective

9.85610978023275*x1_2 + 0.22360679774999168*x1_3 + 10.041956980588992*x2_3 + 0.0

In [56]:
list(map(pulp.value,x))

[1.0, 1.0, 0.0]

In [66]:
a = list(map(int,map(pulp.value,x)))
a

[1, 1, 0]

In [68]:
np.array(x) 

array([x1_2, x1_3, x2_3], dtype=object)

In [63]:
import numpy as np

In [70]:
df['l'] = [1,1,1]

In [71]:
df

lat  long  l
1  140.10  33.2  1
2  130.33  34.5  1
3  140.30  33.3  1

In [72]:
df[['lat','long']]

lat  long
1  140.10  33.2
2  130.33  34.5
3  140.30  33.3